const fakeJourney = {
  data: [
    {
      id: 3,
      label: '',
      category: ['Train'],
      score: '',
      total_distance: 590155.4774831132,
      total_duration: 18835,
      total_price_EUR: 51,
      departure_point: [0, 0],
      arrival_point: [0, 0],
      departure_date: '2020-04-20 16:12:08',
      arrival_date: '2020-04-20 21:26:03',
      total_gCO2: 3670.966273905434,
      is_real_journey: true,
      booking_link: 'https://www.trainline.fr/search/paris/toulouse/2020-04-20 16:00',
      journey_steps: [
        {
          id: '',
          type: 'Walking',
          label: 'Walking FROM 4 Place du Louvre (Paris) TO Pont Neuf - Quai du Louvre (Paris)',
          distance_m: 294,
          duration_s: 263,
          price_EUR: [0],
          departure_point: '4 Place du Louvre (Paris)',
          arrival_point: 'Pont Neuf - Quai du Louvre (Paris)',
          departure_stop_name: '4 Place du Louvre (Paris)',
          arrival_stop_name: 'Pont Neuf - Quai du Louvre (Paris)',
          departure_date: '2020-03-20 15:57:37',
          arrival_date: '2020-03-20 16:02:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 1,
          type: 'Bus',
          label:
            'Bus 58 / Châtelet - Vanves Lycée Michelet / direction: Vanves-Lycee Michelet (Vanves)',
          distance_m: 3014,
          duration_s: 1200,
          price_EUR: [0],
          departure_point: 'Pont Neuf - Quai du Louvre (Paris)',
          arrival_point: 'Gare Montparnasse (Paris)',
          departure_stop_name: 'Pont Neuf - Quai du Louvre (Paris)',
          arrival_stop_name: 'Gare Montparnasse (Paris)',
          departure_date: '2020-03-20 16:02:00',
          arrival_date: '2020-03-20 16:22:00',
          trip_code: '',
          gCO2: 390.9158
        },
        {
          id: 2,
          type: 'Walking',
          label: 'Walking FROM Gare Montparnasse (Paris) TO 20 Place Raoul Dautry (Paris)',
          distance_m: 32,
          duration_s: 29,
          price_EUR: [0],
          departure_point: 'Gare Montparnasse (Paris)',
          arrival_point: '20 Place Raoul Dautry (Paris)',
          departure_stop_name: 'Gare Montparnasse (Paris)',
          arrival_stop_name: '20 Place Raoul Dautry (Paris)',
          departure_date: '2020-03-20 16:22:00',
          arrival_date: '2020-03-20 16:22:29',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 3,
          type: 'Waiting',
          label: 'Arrive at the station 15 minutes before departure',
          distance_m: '',
          duration_s: 900,
          price_EUR: [0],
          departure_point: [48.841172, 2.320514],
          arrival_point: [48.841172, 2.320514],
          departure_stop_name: '',
          arrival_stop_name: '',
          departure_date: '2020-04-20 16:37:00',
          arrival_date: '2020-04-20 16:52:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 4,
          type: 'Train',
          label: 'TGV INOUI 8515 to Toulouse Matabiau',
          distance_m: 585163.4774831132,
          duration_s: 15780,
          price_EUR: [51],
          departure_point: [48.841172, 2.320514],
          arrival_point: [43.611206, 1.453616],
          departure_stop_name: 'Paris Montparnasse',
          arrival_stop_name: 'Toulouse Matabiau',
          departure_date: '2020-04-20 16:52:00',
          arrival_date: '2020-04-20 21:15:00',
          trip_code: 'TGV INOUI 8515',
          gCO2: 3276.915473905434
        },
        {
          id: 54,
          type: 'Walking',
          label: 'Walking FROM 64 Boulevard Pierre Semard (Toulouse) TO Marengo-SNCF (Toulouse)',
          distance_m: 230,
          duration_s: 206,
          price_EUR: [0],
          departure_point: '64 Boulevard Pierre Semard (Toulouse)',
          arrival_point: 'Marengo-SNCF (Toulouse)',
          departure_stop_name: '64 Boulevard Pierre Semard (Toulouse)',
          arrival_stop_name: 'Marengo-SNCF (Toulouse)',
          departure_date: '2020-03-20 15:57:34',
          arrival_date: '2020-03-20 16:01:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 55,
          type: 'unknown public transport',
          label: 'Métro A / Basso Cambo / Balma - Gramont / direction: Basso Cambo (Toulouse)',
          distance_m: 1045,
          duration_s: 120,
          price_EUR: [0],
          departure_point: 'Marengo-SNCF (Toulouse)',
          arrival_point: 'Capitole (Toulouse)',
          departure_stop_name: 'Marengo-SNCF (Toulouse)',
          arrival_stop_name: 'Capitole (Toulouse)',
          departure_date: '2020-03-20 16:01:00',
          arrival_date: '2020-03-20 16:03:00',
          trip_code: '',
          gCO2: 3.135
        },
        {
          id: 56,
          type: 'Walking',
          label: 'Walking FROM Capitole (Toulouse) TO 12 Rue Mirepoix (Toulouse)',
          distance_m: 377,
          duration_s: 337,
          price_EUR: [0],
          departure_point: 'Capitole (Toulouse)',
          arrival_point: '12 Rue Mirepoix (Toulouse)',
          departure_stop_name: 'Capitole (Toulouse)',
          arrival_stop_name: '12 Rue Mirepoix (Toulouse)',
          departure_date: '2020-03-20 16:03:00',
          arrival_date: '2020-03-20 16:08:37',
          trip_code: '',
          gCO2: ''
        }
      ]
    },
    {
      id: 14,
      label: '',
      category: ['Plane'],
      score: '',
      total_distance: 601185.6975916664,
      total_duration: 15006,
      total_price_EUR: 36.4,
      departure_point: [0, 0],
      arrival_point: [0, 0],
      departure_date: '2020-04-20 16:56:58',
      arrival_date: '2020-04-20 21:07:04',
      total_gCO2: 168664.07939435824,
      is_real_journey: true,
      booking_link: 'https://www.skyscanner.fr/transport/vols/pari/tous/200420/',
      journey_steps: [
        {
          id: '',
          type: 'Walking',
          label: 'Walking FROM 4 Place du Louvre (Paris) TO Châtelet les Halles (Paris)',
          distance_m: 614,
          duration_s: 549,
          price_EUR: [0],
          departure_point: '4 Place du Louvre (Paris)',
          arrival_point: 'Châtelet les Halles (Paris)',
          departure_stop_name: '4 Place du Louvre (Paris)',
          arrival_stop_name: 'Châtelet les Halles (Paris)',
          departure_date: '2020-03-20 15:58:51',
          arrival_date: '2020-03-20 16:08:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 1,
          type: 'Metro',
          label:
            'Train de banlieue / RER B / B / direction: Gare de Saint-Rémy les Chevreuse (Saint-Rémy-lès-Chevreuse)',
          distance_m: 12696,
          duration_s: 1200,
          price_EUR: [0],
          departure_point: 'Châtelet les Halles (Paris)',
          arrival_point: "Gare d'Antony (Antony)",
          departure_stop_name: 'Châtelet les Halles (Paris)',
          arrival_stop_name: "Gare d'Antony (Antony)",
          departure_date: '2020-03-20 16:08:00',
          arrival_date: '2020-03-20 16:28:00',
          trip_code: '',
          gCO2: 78.7152
        },
        {
          id: 2,
          type: 'Walking',
          label: "Walking FROM Gare d'Antony (Antony) TO Antony (Antony)",
          distance_m: 23,
          duration_s: 504,
          price_EUR: [0],
          departure_point: "Gare d'Antony (Antony)",
          arrival_point: 'Antony (Antony)',
          departure_stop_name: "Gare d'Antony (Antony)",
          arrival_stop_name: 'Antony (Antony)',
          departure_date: '2020-03-20 16:28:00',
          arrival_date: '2020-03-20 16:36:24',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 3,
          type: 'Waiting',
          label: 'wait',
          distance_m: '',
          duration_s: 336,
          price_EUR: [0],
          departure_point: [0, 0],
          arrival_point: [0, 0],
          departure_stop_name: '',
          arrival_stop_name: '',
          departure_date: '2020-03-20 16:36:24',
          arrival_date: '2020-03-20 16:42:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 4,
          type: 'unknown public transport',
          label: 'Navette ORLYVAL / ORLYVAL / direction: Orly 4 (Paray-Vieille-Poste)',
          distance_m: 5126,
          duration_s: 360,
          price_EUR: [0],
          departure_point: 'Antony (Antony)',
          arrival_point: 'Orly 1-2-3 (Paray-Vieille-Poste)',
          departure_stop_name: 'Antony (Antony)',
          arrival_stop_name: 'Orly 1-2-3 (Paray-Vieille-Poste)',
          departure_date: '2020-03-20 16:42:00',
          arrival_date: '2020-03-20 16:48:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 5,
          type: 'Walking',
          label:
            'Walking FROM Orly 1-2-3 (Paray-Vieille-Poste) TO Rue des Transporteurs (Paray-Vieille-Poste)',
          distance_m: 596,
          duration_s: 533,
          price_EUR: [0],
          departure_point: 'Orly 1-2-3 (Paray-Vieille-Poste)',
          arrival_point: 'Rue des Transporteurs (Paray-Vieille-Poste)',
          departure_stop_name: 'Orly 1-2-3 (Paray-Vieille-Poste)',
          arrival_stop_name: 'Rue des Transporteurs (Paray-Vieille-Poste)',
          departure_date: '2020-03-20 16:48:00',
          arrival_date: '2020-03-20 16:56:53',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 6,
          type: 'Waiting',
          label: 'Arrive at the airport 1 hour and 15 minutes before departure',
          distance_m: '',
          duration_s: 4500,
          price_EUR: [0],
          departure_point: [48.725, 2.359],
          arrival_point: [48.725, 2.359],
          departure_stop_name: '',
          arrival_stop_name: '',
          departure_date: '2020-04-20 17:55:00',
          arrival_date: '2020-04-20 19:10:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 7,
          type: 'Plane',
          label: 'Flight U24033 to Toulouse',
          distance_m: 571616.6975916664,
          duration_s: 4500,
          price_EUR: [36.4],
          departure_point: [48.725, 2.359],
          arrival_point: [43.629, 1.364],
          departure_stop_name: 'Paris Orly',
          arrival_stop_name: 'Toulouse',
          departure_date: '2020-04-20 19:10:00',
          arrival_date: '2020-04-20 20:25:00',
          trip_code: 'U24033',
          gCO2: 167483.69239435822
        },
        {
          id: 26,
          type: 'Walking',
          label: 'Walking FROM Allée Saint-Exupéry (Blagnac) TO Aéroport (Blagnac)',
          distance_m: 1085,
          duration_s: 969,
          price_EUR: [0],
          departure_point: 'Allée Saint-Exupéry (Blagnac)',
          arrival_point: 'Aéroport (Blagnac)',
          departure_stop_name: 'Allée Saint-Exupéry (Blagnac)',
          arrival_stop_name: 'Aéroport (Blagnac)',
          departure_date: '2020-03-20 15:58:51',
          arrival_date: '2020-03-20 16:15:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 27,
          type: 'Bus',
          label: 'Bus AERO / Navette Aéroport / direction: Gare Routière (Toulouse)',
          distance_m: 8494,
          duration_s: 720,
          price_EUR: [0],
          departure_point: 'Aéroport (Blagnac)',
          arrival_point: 'Compans-Caffarelli (Toulouse)',
          departure_stop_name: 'Aéroport (Blagnac)',
          arrival_stop_name: 'Compans-Caffarelli (Toulouse)',
          departure_date: '2020-03-20 16:15:00',
          arrival_date: '2020-03-20 16:27:00',
          trip_code: '',
          gCO2: 1101.6718
        },
        {
          id: 28,
          type: 'Walking',
          label: 'Walking FROM Compans-Caffarelli (Toulouse) TO 12 Rue Mirepoix (Toulouse)',
          distance_m: 935,
          duration_s: 835,
          price_EUR: [0],
          departure_point: 'Compans-Caffarelli (Toulouse)',
          arrival_point: '12 Rue Mirepoix (Toulouse)',
          departure_stop_name: 'Compans-Caffarelli (Toulouse)',
          arrival_stop_name: '12 Rue Mirepoix (Toulouse)',
          departure_date: '2020-03-20 16:27:00',
          arrival_date: '2020-03-20 16:40:55',
          trip_code: '',
          gCO2: ''
        }
      ]
    },
    {
      id: 12,
      label: '',
      category: ['Plane'],
      score: '',
      total_distance: 640086.2911934933,
      total_duration: 14999,
      total_price_EUR: 29.4,
      departure_point: [0, 0],
      arrival_point: [0, 0],
      departure_date: '2020-04-20 19:22:05',
      arrival_date: '2020-04-20 23:32:04',
      total_gCO2: 178619.79811969353,
      is_real_journey: true,
      booking_link: 'https://www.skyscanner.fr/transport/vols/pari/tous/200420/',
      journey_steps: [
        {
          id: '',
          type: 'Walking',
          label: 'Walking FROM 4 Place du Louvre (Paris) TO Châtelet les Halles (Paris)',
          distance_m: 614,
          duration_s: 549,
          price_EUR: [0],
          departure_point: '4 Place du Louvre (Paris)',
          arrival_point: 'Châtelet les Halles (Paris)',
          departure_stop_name: '4 Place du Louvre (Paris)',
          arrival_stop_name: 'Châtelet les Halles (Paris)',
          departure_date: '2020-03-20 15:58:51',
          arrival_date: '2020-03-20 16:08:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 1,
          type: 'Metro',
          label:
            'Train de banlieue / RER B / B / direction: Aéroport CDG 2 TGV (Tremblay-en-France)',
          distance_m: 22855,
          duration_s: 1680,
          price_EUR: [0],
          departure_point: 'Châtelet les Halles (Paris)',
          arrival_point: 'Aéroport CDG 1 (Tremblay-en-France)',
          departure_stop_name: 'Châtelet les Halles (Paris)',
          arrival_stop_name: 'Aéroport CDG 1 (Tremblay-en-France)',
          departure_date: '2020-03-20 16:08:00',
          arrival_date: '2020-03-20 16:36:00',
          trip_code: '',
          gCO2: 141.701
        },
        {
          id: 2,
          type: 'Walking',
          label:
            'Walking FROM Aéroport CDG 1 (Tremblay-en-France) TO Route des Peupliers (Roissy-en-France)',
          distance_m: 723,
          duration_s: 646,
          price_EUR: [0],
          departure_point: 'Aéroport CDG 1 (Tremblay-en-France)',
          arrival_point: 'Route des Peupliers (Roissy-en-France)',
          departure_stop_name: 'Aéroport CDG 1 (Tremblay-en-France)',
          arrival_stop_name: 'Route des Peupliers (Roissy-en-France)',
          departure_date: '2020-03-20 16:36:00',
          arrival_date: '2020-03-20 16:46:46',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 3,
          type: 'Waiting',
          label: 'Arrive at the airport 1 hour and 15 minutes before departure',
          distance_m: '',
          duration_s: 4500,
          price_EUR: [0],
          departure_point: [49.013000000000005, 2.55],
          arrival_point: [49.013000000000005, 2.55],
          departure_stop_name: '',
          arrival_stop_name: '',
          departure_date: '2020-04-20 20:10:00',
          arrival_date: '2020-04-20 21:25:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 4,
          type: 'Plane',
          label: 'Flight U23965 to Toulouse',
          distance_m: 605380.2911934933,
          duration_s: 5100,
          price_EUR: [29.4],
          departure_point: [49.013000000000005, 2.55],
          arrival_point: [43.629, 1.364],
          departure_stop_name: 'Paris Charles de Gaulle',
          arrival_stop_name: 'Toulouse',
          departure_date: '2020-04-20 21:25:00',
          arrival_date: '2020-04-20 22:50:00',
          trip_code: 'U23965',
          gCO2: 177376.42531969352
        },
        {
          id: 26,
          type: 'Walking',
          label: 'Walking FROM Allée Saint-Exupéry (Blagnac) TO Aéroport (Blagnac)',
          distance_m: 1085,
          duration_s: 969,
          price_EUR: [0],
          departure_point: 'Allée Saint-Exupéry (Blagnac)',
          arrival_point: 'Aéroport (Blagnac)',
          departure_stop_name: 'Allée Saint-Exupéry (Blagnac)',
          arrival_stop_name: 'Aéroport (Blagnac)',
          departure_date: '2020-03-20 15:58:51',
          arrival_date: '2020-03-20 16:15:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 27,
          type: 'Bus',
          label: 'Bus AERO / Navette Aéroport / direction: Gare Routière (Toulouse)',
          distance_m: 8494,
          duration_s: 720,
          price_EUR: [0],
          departure_point: 'Aéroport (Blagnac)',
          arrival_point: 'Compans-Caffarelli (Toulouse)',
          departure_stop_name: 'Aéroport (Blagnac)',
          arrival_stop_name: 'Compans-Caffarelli (Toulouse)',
          departure_date: '2020-03-20 16:15:00',
          arrival_date: '2020-03-20 16:27:00',
          trip_code: '',
          gCO2: 1101.6718
        },
        {
          id: 28,
          type: 'Walking',
          label: 'Walking FROM Compans-Caffarelli (Toulouse) TO 12 Rue Mirepoix (Toulouse)',
          distance_m: 935,
          duration_s: 835,
          price_EUR: [0],
          departure_point: 'Compans-Caffarelli (Toulouse)',
          arrival_point: '12 Rue Mirepoix (Toulouse)',
          departure_stop_name: 'Compans-Caffarelli (Toulouse)',
          arrival_stop_name: '12 Rue Mirepoix (Toulouse)',
          departure_date: '2020-03-20 16:27:00',
          arrival_date: '2020-03-20 16:40:55',
          trip_code: '',
          gCO2: ''
        }
      ]
    },
    {
      id: 4,
      label: 'Cleanest Journey',
      category: ['Train'],
      score: '',
      total_distance: 590396.2249806329,
      total_duration: 26783,
      total_price_EUR: 15,
      departure_point: [0, 0],
      arrival_point: [0, 0],
      departure_date: '2020-04-21 04:05:40',
      arrival_date: '2020-04-21 11:32:03',
      total_gCO2: 3294.7206598915445,
      is_real_journey: true,
      booking_link: 'https://www.trainline.fr/search/paris/toulouse/2020-04-21 04:00',
      journey_steps: [
        {
          id: '',
          type: 'Walking',
          label: 'Walking FROM 4 Place du Louvre (Paris) TO Saint-Michel Notre-Dame RER C (Paris)',
          distance_m: 1004,
          duration_s: 897,
          price_EUR: [0],
          departure_point: '4 Place du Louvre (Paris)',
          arrival_point: 'Saint-Michel Notre-Dame RER C (Paris)',
          departure_stop_name: '4 Place du Louvre (Paris)',
          arrival_stop_name: 'Saint-Michel Notre-Dame RER C (Paris)',
          departure_date: '2020-03-20 15:58:03',
          arrival_date: '2020-03-20 16:13:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 1,
          type: 'Metro',
          label: 'Train de banlieue / RER C / C / direction: Gare de Dourdan la Foret (Dourdan)',
          distance_m: 1894,
          duration_s: 180,
          price_EUR: [0],
          departure_point: 'Saint-Michel Notre-Dame RER C (Paris)',
          arrival_point: "Gare d'Austerlitz RER C (Paris)",
          departure_stop_name: 'Saint-Michel Notre-Dame RER C (Paris)',
          arrival_stop_name: "Gare d'Austerlitz RER C (Paris)",
          departure_date: '2020-03-20 16:13:00',
          arrival_date: '2020-03-20 16:16:00',
          trip_code: '',
          gCO2: 11.7428
        },
        {
          id: 2,
          type: 'Walking',
          label: "Walking FROM Gare d'Austerlitz RER C (Paris) TO 5 Boulevard de l'Hôpital (Paris)",
          distance_m: 160,
          duration_s: 143,
          price_EUR: [0],
          departure_point: "Gare d'Austerlitz RER C (Paris)",
          arrival_point: "5 Boulevard de l'Hôpital (Paris)",
          departure_stop_name: "Gare d'Austerlitz RER C (Paris)",
          arrival_stop_name: "5 Boulevard de l'Hôpital (Paris)",
          departure_date: '2020-03-20 16:16:00',
          arrival_date: '2020-03-20 16:18:23',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 3,
          type: 'Waiting',
          label: 'Arrive at the station 15 minutes before departure',
          distance_m: '',
          duration_s: 900,
          price_EUR: [0],
          departure_point: [48.842285, 2.364891],
          arrival_point: [48.842285, 2.364891],
          departure_stop_name: '',
          arrival_stop_name: '',
          departure_date: '2020-04-21 04:26:00',
          arrival_date: '2020-04-21 04:41:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 4,
          type: 'Train',
          label: 'IC 3605 to Toulouse Matabiau',
          distance_m: 585686.2249806329,
          duration_s: 24000,
          price_EUR: [15],
          departure_point: [48.842285, 2.364891],
          arrival_point: [43.611206, 1.453616],
          departure_stop_name: 'Paris Austerlitz',
          arrival_stop_name: 'Toulouse Matabiau',
          departure_date: '2020-04-21 04:41:00',
          arrival_date: '2020-04-21 11:21:00',
          trip_code: 'IC 3605',
          gCO2: 3279.8428598915443
        },
        {
          id: 54,
          type: 'Walking',
          label: 'Walking FROM 64 Boulevard Pierre Semard (Toulouse) TO Marengo-SNCF (Toulouse)',
          distance_m: 230,
          duration_s: 206,
          price_EUR: [0],
          departure_point: '64 Boulevard Pierre Semard (Toulouse)',
          arrival_point: 'Marengo-SNCF (Toulouse)',
          departure_stop_name: '64 Boulevard Pierre Semard (Toulouse)',
          arrival_stop_name: 'Marengo-SNCF (Toulouse)',
          departure_date: '2020-03-20 15:57:34',
          arrival_date: '2020-03-20 16:01:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 55,
          type: 'unknown public transport',
          label: 'Métro A / Basso Cambo / Balma - Gramont / direction: Basso Cambo (Toulouse)',
          distance_m: 1045,
          duration_s: 120,
          price_EUR: [0],
          departure_point: 'Marengo-SNCF (Toulouse)',
          arrival_point: 'Capitole (Toulouse)',
          departure_stop_name: 'Marengo-SNCF (Toulouse)',
          arrival_stop_name: 'Capitole (Toulouse)',
          departure_date: '2020-03-20 16:01:00',
          arrival_date: '2020-03-20 16:03:00',
          trip_code: '',
          gCO2: 3.135
        },
        {
          id: 56,
          type: 'Walking',
          label: 'Walking FROM Capitole (Toulouse) TO 12 Rue Mirepoix (Toulouse)',
          distance_m: 377,
          duration_s: 337,
          price_EUR: [0],
          departure_point: 'Capitole (Toulouse)',
          arrival_point: '12 Rue Mirepoix (Toulouse)',
          departure_stop_name: 'Capitole (Toulouse)',
          arrival_stop_name: '12 Rue Mirepoix (Toulouse)',
          departure_date: '2020-03-20 16:03:00',
          arrival_date: '2020-03-20 16:08:37',
          trip_code: '',
          gCO2: ''
        }
      ]
    },
    {
      id: '',
      label: '',
      category: ['Car'],
      score: '',
      total_distance: 676473.4,
      total_duration: 23371.4,
      total_price_EUR: 84.28858564,
      departure_point: [0, 0],
      arrival_point: [0, 0],
      departure_date: '2020-03-20 04:35:11.456563',
      arrival_date: '2020-03-20 11:04:42.856563',
      total_gCO2: 104176.9036,
      is_real_journey: true,
      booking_link: '',
      journey_steps: [
        {
          id: '',
          type: 'Car',
          label: 'driving-car',
          distance_m: 676473.4,
          duration_s: 23371.4,
          price_EUR: [67.37675064, 16.911835],
          departure_point: [0],
          arrival_point: [0],
          departure_stop_name: '',
          arrival_stop_name: '',
          departure_date: '2020-03-20 04:35:11.456637',
          arrival_date: '2020-03-20 11:04:42.856637',
          trip_code: '',
          gCO2: 104176.9036
        }
      ]
    },
    {
      id: 10,
      label: '',
      category: ['Plane'],
      score: '',
      total_distance: 601185.6975916664,
      total_duration: 15006,
      total_price_EUR: 34.9,
      departure_point: [0, 0],
      arrival_point: [0, 0],
      departure_date: '2020-04-20 15:56:58',
      arrival_date: '2020-04-20 20:07:04',
      total_gCO2: 168664.07939435824,
      is_real_journey: true,
      booking_link: 'https://www.skyscanner.fr/transport/vols/pari/tous/200420/',
      journey_steps: [
        {
          id: '',
          type: 'Walking',
          label: 'Walking FROM 4 Place du Louvre (Paris) TO Châtelet les Halles (Paris)',
          distance_m: 614,
          duration_s: 549,
          price_EUR: [0],
          departure_point: '4 Place du Louvre (Paris)',
          arrival_point: 'Châtelet les Halles (Paris)',
          departure_stop_name: '4 Place du Louvre (Paris)',
          arrival_stop_name: 'Châtelet les Halles (Paris)',
          departure_date: '2020-03-20 15:58:51',
          arrival_date: '2020-03-20 16:08:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 1,
          type: 'Metro',
          label:
            'Train de banlieue / RER B / B / direction: Gare de Saint-Rémy les Chevreuse (Saint-Rémy-lès-Chevreuse)',
          distance_m: 12696,
          duration_s: 1200,
          price_EUR: [0],
          departure_point: 'Châtelet les Halles (Paris)',
          arrival_point: "Gare d'Antony (Antony)",
          departure_stop_name: 'Châtelet les Halles (Paris)',
          arrival_stop_name: "Gare d'Antony (Antony)",
          departure_date: '2020-03-20 16:08:00',
          arrival_date: '2020-03-20 16:28:00',
          trip_code: '',
          gCO2: 78.7152
        },
        {
          id: 2,
          type: 'Walking',
          label: "Walking FROM Gare d'Antony (Antony) TO Antony (Antony)",
          distance_m: 23,
          duration_s: 504,
          price_EUR: [0],
          departure_point: "Gare d'Antony (Antony)",
          arrival_point: 'Antony (Antony)',
          departure_stop_name: "Gare d'Antony (Antony)",
          arrival_stop_name: 'Antony (Antony)',
          departure_date: '2020-03-20 16:28:00',
          arrival_date: '2020-03-20 16:36:24',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 3,
          type: 'Waiting',
          label: 'wait',
          distance_m: '',
          duration_s: 336,
          price_EUR: [0],
          departure_point: [0, 0],
          arrival_point: [0, 0],
          departure_stop_name: '',
          arrival_stop_name: '',
          departure_date: '2020-03-20 16:36:24',
          arrival_date: '2020-03-20 16:42:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 4,
          type: 'unknown public transport',
          label: 'Navette ORLYVAL / ORLYVAL / direction: Orly 4 (Paray-Vieille-Poste)',
          distance_m: 5126,
          duration_s: 360,
          price_EUR: [0],
          departure_point: 'Antony (Antony)',
          arrival_point: 'Orly 1-2-3 (Paray-Vieille-Poste)',
          departure_stop_name: 'Antony (Antony)',
          arrival_stop_name: 'Orly 1-2-3 (Paray-Vieille-Poste)',
          departure_date: '2020-03-20 16:42:00',
          arrival_date: '2020-03-20 16:48:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 5,
          type: 'Walking',
          label:
            'Walking FROM Orly 1-2-3 (Paray-Vieille-Poste) TO Rue des Transporteurs (Paray-Vieille-Poste)',
          distance_m: 596,
          duration_s: 533,
          price_EUR: [0],
          departure_point: 'Orly 1-2-3 (Paray-Vieille-Poste)',
          arrival_point: 'Rue des Transporteurs (Paray-Vieille-Poste)',
          departure_stop_name: 'Orly 1-2-3 (Paray-Vieille-Poste)',
          arrival_stop_name: 'Rue des Transporteurs (Paray-Vieille-Poste)',
          departure_date: '2020-03-20 16:48:00',
          arrival_date: '2020-03-20 16:56:53',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 6,
          type: 'Waiting',
          label: 'Arrive at the airport 1 hour and 15 minutes before departure',
          distance_m: '',
          duration_s: 4500,
          price_EUR: [0],
          departure_point: [48.725, 2.359],
          arrival_point: [48.725, 2.359],
          departure_stop_name: '',
          arrival_stop_name: '',
          departure_date: '2020-04-20 16:55:00',
          arrival_date: '2020-04-20 18:10:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 7,
          type: 'Plane',
          label: 'Flight U24031 to Toulouse',
          distance_m: 571616.6975916664,
          duration_s: 4500,
          price_EUR: [34.9],
          departure_point: [48.725, 2.359],
          arrival_point: [43.629, 1.364],
          departure_stop_name: 'Paris Orly',
          arrival_stop_name: 'Toulouse',
          departure_date: '2020-04-20 18:10:00',
          arrival_date: '2020-04-20 19:25:00',
          trip_code: 'U24031',
          gCO2: 167483.69239435822
        },
        {
          id: 26,
          type: 'Walking',
          label: 'Walking FROM Allée Saint-Exupéry (Blagnac) TO Aéroport (Blagnac)',
          distance_m: 1085,
          duration_s: 969,
          price_EUR: [0],
          departure_point: 'Allée Saint-Exupéry (Blagnac)',
          arrival_point: 'Aéroport (Blagnac)',
          departure_stop_name: 'Allée Saint-Exupéry (Blagnac)',
          arrival_stop_name: 'Aéroport (Blagnac)',
          departure_date: '2020-03-20 15:58:51',
          arrival_date: '2020-03-20 16:15:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 27,
          type: 'Bus',
          label: 'Bus AERO / Navette Aéroport / direction: Gare Routière (Toulouse)',
          distance_m: 8494,
          duration_s: 720,
          price_EUR: [0],
          departure_point: 'Aéroport (Blagnac)',
          arrival_point: 'Compans-Caffarelli (Toulouse)',
          departure_stop_name: 'Aéroport (Blagnac)',
          arrival_stop_name: 'Compans-Caffarelli (Toulouse)',
          departure_date: '2020-03-20 16:15:00',
          arrival_date: '2020-03-20 16:27:00',
          trip_code: '',
          gCO2: 1101.6718
        },
        {
          id: 28,
          type: 'Walking',
          label: 'Walking FROM Compans-Caffarelli (Toulouse) TO 12 Rue Mirepoix (Toulouse)',
          distance_m: 935,
          duration_s: 835,
          price_EUR: [0],
          departure_point: 'Compans-Caffarelli (Toulouse)',
          arrival_point: '12 Rue Mirepoix (Toulouse)',
          departure_stop_name: 'Compans-Caffarelli (Toulouse)',
          arrival_stop_name: '12 Rue Mirepoix (Toulouse)',
          departure_date: '2020-03-20 16:27:00',
          arrival_date: '2020-03-20 16:40:55',
          trip_code: '',
          gCO2: ''
        }
      ]
    },
    {
      id: 11,
      label: 'Fastest Journey',
      category: ['Plane'],
      score: '',
      total_distance: 640086.2911934933,
      total_duration: 14699,
      total_price_EUR: 69,
      departure_point: [0, 0],
      arrival_point: [0, 0],
      departure_date: '2020-04-20 16:32:05',
      arrival_date: '2020-04-20 20:37:04',
      total_gCO2: 178619.79811969353,
      is_real_journey: true,
      booking_link: 'https://www.skyscanner.fr/transport/vols/pari/tous/200420/',
      journey_steps: [
        {
          id: '',
          type: 'Walking',
          label: 'Walking FROM 4 Place du Louvre (Paris) TO Châtelet les Halles (Paris)',
          distance_m: 614,
          duration_s: 549,
          price_EUR: [0],
          departure_point: '4 Place du Louvre (Paris)',
          arrival_point: 'Châtelet les Halles (Paris)',
          departure_stop_name: '4 Place du Louvre (Paris)',
          arrival_stop_name: 'Châtelet les Halles (Paris)',
          departure_date: '2020-03-20 15:58:51',
          arrival_date: '2020-03-20 16:08:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 1,
          type: 'Metro',
          label:
            'Train de banlieue / RER B / B / direction: Aéroport CDG 2 TGV (Tremblay-en-France)',
          distance_m: 22855,
          duration_s: 1680,
          price_EUR: [0],
          departure_point: 'Châtelet les Halles (Paris)',
          arrival_point: 'Aéroport CDG 1 (Tremblay-en-France)',
          departure_stop_name: 'Châtelet les Halles (Paris)',
          arrival_stop_name: 'Aéroport CDG 1 (Tremblay-en-France)',
          departure_date: '2020-03-20 16:08:00',
          arrival_date: '2020-03-20 16:36:00',
          trip_code: '',
          gCO2: 141.701
        },
        {
          id: 2,
          type: 'Walking',
          label:
            'Walking FROM Aéroport CDG 1 (Tremblay-en-France) TO Route des Peupliers (Roissy-en-France)',
          distance_m: 723,
          duration_s: 646,
          price_EUR: [0],
          departure_point: 'Aéroport CDG 1 (Tremblay-en-France)',
          arrival_point: 'Route des Peupliers (Roissy-en-France)',
          departure_stop_name: 'Aéroport CDG 1 (Tremblay-en-France)',
          arrival_stop_name: 'Route des Peupliers (Roissy-en-France)',
          departure_date: '2020-03-20 16:36:00',
          arrival_date: '2020-03-20 16:46:46',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 3,
          type: 'Waiting',
          label: 'Arrive at the airport 1 hour and 15 minutes before departure',
          distance_m: '',
          duration_s: 4500,
          price_EUR: [0],
          departure_point: [49.013000000000005, 2.55],
          arrival_point: [49.013000000000005, 2.55],
          departure_stop_name: '',
          arrival_stop_name: '',
          departure_date: '2020-04-20 17:20:00',
          arrival_date: '2020-04-20 18:35:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 4,
          type: 'Plane',
          label: 'Flight AF7524 to Toulouse',
          distance_m: 605380.2911934933,
          duration_s: 4800,
          price_EUR: [69],
          departure_point: [49.013000000000005, 2.55],
          arrival_point: [43.629, 1.364],
          departure_stop_name: 'Paris Charles de Gaulle',
          arrival_stop_name: 'Toulouse',
          departure_date: '2020-04-20 18:35:00',
          arrival_date: '2020-04-20 19:55:00',
          trip_code: 'AF7524',
          gCO2: 177376.42531969352
        },
        {
          id: 26,
          type: 'Walking',
          label: 'Walking FROM Allée Saint-Exupéry (Blagnac) TO Aéroport (Blagnac)',
          distance_m: 1085,
          duration_s: 969,
          price_EUR: [0],
          departure_point: 'Allée Saint-Exupéry (Blagnac)',
          arrival_point: 'Aéroport (Blagnac)',
          departure_stop_name: 'Allée Saint-Exupéry (Blagnac)',
          arrival_stop_name: 'Aéroport (Blagnac)',
          departure_date: '2020-03-20 15:58:51',
          arrival_date: '2020-03-20 16:15:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 27,
          type: 'Bus',
          label: 'Bus AERO / Navette Aéroport / direction: Gare Routière (Toulouse)',
          distance_m: 8494,
          duration_s: 720,
          price_EUR: [0],
          departure_point: 'Aéroport (Blagnac)',
          arrival_point: 'Compans-Caffarelli (Toulouse)',
          departure_stop_name: 'Aéroport (Blagnac)',
          arrival_stop_name: 'Compans-Caffarelli (Toulouse)',
          departure_date: '2020-03-20 16:15:00',
          arrival_date: '2020-03-20 16:27:00',
          trip_code: '',
          gCO2: 1101.6718
        },
        {
          id: 28,
          type: 'Walking',
          label: 'Walking FROM Compans-Caffarelli (Toulouse) TO 12 Rue Mirepoix (Toulouse)',
          distance_m: 935,
          duration_s: 835,
          price_EUR: [0],
          departure_point: 'Compans-Caffarelli (Toulouse)',
          arrival_point: '12 Rue Mirepoix (Toulouse)',
          departure_stop_name: 'Compans-Caffarelli (Toulouse)',
          arrival_stop_name: '12 Rue Mirepoix (Toulouse)',
          departure_date: '2020-03-20 16:27:00',
          arrival_date: '2020-03-20 16:40:55',
          trip_code: '',
          gCO2: ''
        }
      ]
    },
    {
      id: 5,
      label: '',
      category: ['Train'],
      score: '',
      total_distance: 590396.2249806329,
      total_duration: 26783,
      total_price_EUR: 23,
      departure_point: [0, 0],
      arrival_point: [0, 0],
      departure_date: '2020-04-21 04:05:40',
      arrival_date: '2020-04-21 11:32:03',
      total_gCO2: 3294.7206598915445,
      is_real_journey: true,
      booking_link: 'https://www.trainline.fr/search/paris/toulouse/2020-04-21 04:00',
      journey_steps: [
        {
          id: '',
          type: 'Walking',
          label: 'Walking FROM 4 Place du Louvre (Paris) TO Saint-Michel Notre-Dame RER C (Paris)',
          distance_m: 1004,
          duration_s: 897,
          price_EUR: [0],
          departure_point: '4 Place du Louvre (Paris)',
          arrival_point: 'Saint-Michel Notre-Dame RER C (Paris)',
          departure_stop_name: '4 Place du Louvre (Paris)',
          arrival_stop_name: 'Saint-Michel Notre-Dame RER C (Paris)',
          departure_date: '2020-03-20 15:58:03',
          arrival_date: '2020-03-20 16:13:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 1,
          type: 'Metro',
          label: 'Train de banlieue / RER C / C / direction: Gare de Dourdan la Foret (Dourdan)',
          distance_m: 1894,
          duration_s: 180,
          price_EUR: [0],
          departure_point: 'Saint-Michel Notre-Dame RER C (Paris)',
          arrival_point: "Gare d'Austerlitz RER C (Paris)",
          departure_stop_name: 'Saint-Michel Notre-Dame RER C (Paris)',
          arrival_stop_name: "Gare d'Austerlitz RER C (Paris)",
          departure_date: '2020-03-20 16:13:00',
          arrival_date: '2020-03-20 16:16:00',
          trip_code: '',
          gCO2: 11.7428
        },
        {
          id: 2,
          type: 'Walking',
          label: "Walking FROM Gare d'Austerlitz RER C (Paris) TO 5 Boulevard de l'Hôpital (Paris)",
          distance_m: 160,
          duration_s: 143,
          price_EUR: [0],
          departure_point: "Gare d'Austerlitz RER C (Paris)",
          arrival_point: "5 Boulevard de l'Hôpital (Paris)",
          departure_stop_name: "Gare d'Austerlitz RER C (Paris)",
          arrival_stop_name: "5 Boulevard de l'Hôpital (Paris)",
          departure_date: '2020-03-20 16:16:00',
          arrival_date: '2020-03-20 16:18:23',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 3,
          type: 'Waiting',
          label: 'Arrive at the station 15 minutes before departure',
          distance_m: '',
          duration_s: 900,
          price_EUR: [0],
          departure_point: [48.842285, 2.364891],
          arrival_point: [48.842285, 2.364891],
          departure_stop_name: '',
          arrival_stop_name: '',
          departure_date: '2020-04-21 04:26:00',
          arrival_date: '2020-04-21 04:41:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 4,
          type: 'Train',
          label: 'IC 3605 to Toulouse Matabiau',
          distance_m: 585686.2249806329,
          duration_s: 24000,
          price_EUR: [23],
          departure_point: [48.842285, 2.364891],
          arrival_point: [43.611206, 1.453616],
          departure_stop_name: 'Paris Austerlitz',
          arrival_stop_name: 'Toulouse Matabiau',
          departure_date: '2020-04-21 04:41:00',
          arrival_date: '2020-04-21 11:21:00',
          trip_code: 'IC 3605',
          gCO2: 3279.8428598915443
        },
        {
          id: 54,
          type: 'Walking',
          label: 'Walking FROM 64 Boulevard Pierre Semard (Toulouse) TO Marengo-SNCF (Toulouse)',
          distance_m: 230,
          duration_s: 206,
          price_EUR: [0],
          departure_point: '64 Boulevard Pierre Semard (Toulouse)',
          arrival_point: 'Marengo-SNCF (Toulouse)',
          departure_stop_name: '64 Boulevard Pierre Semard (Toulouse)',
          arrival_stop_name: 'Marengo-SNCF (Toulouse)',
          departure_date: '2020-03-20 15:57:34',
          arrival_date: '2020-03-20 16:01:00',
          trip_code: '',
          gCO2: ''
        },
        {
          id: 55,
          type: 'unknown public transport',
          label: 'Métro A / Basso Cambo / Balma - Gramont / direction: Basso Cambo (Toulouse)',
          distance_m: 1045,
          duration_s: 120,
          price_EUR: [0],
          departure_point: 'Marengo-SNCF (Toulouse)',
          arrival_point: 'Capitole (Toulouse)',
          departure_stop_name: 'Marengo-SNCF (Toulouse)',
          arrival_stop_name: 'Capitole (Toulouse)',
          departure_date: '2020-03-20 16:01:00',
          arrival_date: '2020-03-20 16:03:00',
          trip_code: '',
          gCO2: 3.135
        },
        {
          id: 56,
          type: 'Walking',
          label: 'Walking FROM Capitole (Toulouse) TO 12 Rue Mirepoix (Toulouse)',
          distance_m: 377,
          duration_s: 337,
          price_EUR: [0],
          departure_point: 'Capitole (Toulouse)',
          arrival_point: '12 Rue Mirepoix (Toulouse)',
          departure_stop_name: 'Capitole (Toulouse)',
          arrival_stop_name: '12 Rue Mirepoix (Toulouse)',
          departure_date: '2020-03-20 16:03:00',
          arrival_date: '2020-03-20 16:08:37',
          trip_code: '',
          gCO2: ''
        }
      ]
    }
  ]
}

export default fakeJourney
